import { Test, TestingModule } from '@nestjs/testing';
import { INestApplication, ValidationPipe } from '@nestjs/common';
import request from 'supertest';
import { AppModule } from '../src/app.module';
import { getRepositoryToken } from '@nestjs/typeorm';
import { Repository } from 'typeorm';
import { User } from '../src/users/entities/user.entity';
import { VerificationToken } from '../src/verification/entities/verification-token.entity';
import { GuestSession } from '../src/guest-session/entities/guest-session.entity';
import { GlobalExceptionFilter } from '../src/common/filters/global-exception.filter';

describe('Authentication Flow (e2e)', () => {
  let app: INestApplication;
  let userRepository: Repository<User>;
  let verificationRepository: Repository<VerificationToken>;
  let guestSessionRepository: Repository<GuestSession>;

  const testUser = {
    firstName: 'E2E',
    lastName: 'Tester',
    email: 'e2e.test@example.com',
    password: 'SecurePassword123!',
    passwordConfirm: 'SecurePassword123!',
  };

  beforeAll(async () => {
    const moduleFixture: TestingModule = await Test.createTestingModule({
      imports: [AppModule],
    }).compile();

    app = moduleFixture.createNestApplication();
    app.useGlobalFilters(new GlobalExceptionFilter());
    app.useGlobalPipes(
      new ValidationPipe({
        whitelist: true,
        forbidNonWhitelisted: true,
      }),
    );

    await app.init();

    userRepository = moduleFixture.get<Repository<User>>(getRepositoryToken(User));
    verificationRepository = moduleFixture.get<Repository<VerificationToken>>(
      getRepositoryToken(VerificationToken),
    );
    guestSessionRepository = moduleFixture.get<Repository<GuestSession>>(
      getRepositoryToken(GuestSession),
    );

    // Initial database cleanup to prevent duplicate errors from prior failed test runs
    const existingUser = await userRepository.findOne({ where: { email: testUser.email } });
    if (existingUser) {
      await verificationRepository.delete({ user: { id: existingUser.id } });
      await userRepository.delete(existingUser.id);
    }
    await guestSessionRepository.delete({ guestId: '12345678-1234-1234-1234-123456789012' });
  });

  afterAll(async () => {
    // Cleanup database records generated by the test
    const user = await userRepository.findOne({ where: { email: testUser.email } });
    if (user) {
      await verificationRepository.delete({ user: { id: user.id } });
      await userRepository.delete(user.id);
    }
    await guestSessionRepository.delete({ guestId: '12345678-1234-1234-1234-123456789012' });
    await app.close();
  });

  let guestToken: string;
  let verificationTokenString: string;
  let accessToken: string;
  let refreshToken: string;

  it('1. POST /get_token (Get Guest Token)', async () => {
    const res = await request(app.getHttpServer())
      .post('/get_token')
      .expect(201);

    expect(res.body).toHaveProperty('guestToken');
    guestToken = res.body.guestToken;
  });

  it('2. POST /auth/register (Register with Guest Token)', async () => {
    const res = await request(app.getHttpServer())
      .post('/auth/register')
      .set('Authorization', `Bearer ${guestToken}`)
      .send(testUser)
      .expect(201);

    expect(res.body).toHaveProperty('message');
    expect(res.body.message).toContain('successful');

    // Retrieve the generated verification token from the database
    const user = await userRepository.findOne({ where: { email: testUser.email } });
    expect(user).toBeDefined();

    const tokenRecord = await verificationRepository.findOne({
      where: { user: { id: user!.id } },
    });
    expect(tokenRecord).toBeDefined();
    verificationTokenString = tokenRecord!.token;
  });

  it('3. POST /auth/login (Login before verification - Should Fail)', async () => {
    const res = await request(app.getHttpServer())
      .post('/auth/login')
      .set('Authorization', `Bearer ${guestToken}`)
      .send({
        email: testUser.email,
        password: testUser.password,
      })
      .expect(400);

    expect(res.body).toHaveProperty('success', false);
    expect(res.body).toHaveProperty('message', 'Email not verified');
  });

  it('4. GET /auth/verify (Verify Email using token)', async () => {
    await request(app.getHttpServer())
      .get(`/auth/verify?token=${verificationTokenString}`)
      .expect(200);

    // Verify token was deleted after use
    const tokenRecord = await verificationRepository.findOne({
      where: { token: verificationTokenString },
    });
    expect(tokenRecord).toBeNull();
  });

  it('5. POST /auth/login (Login after verification - Should Succeed)', async () => {
    const res = await request(app.getHttpServer())
      .post('/auth/login')
      .set('Authorization', `Bearer ${guestToken}`)
      .send({
        email: testUser.email,
        password: testUser.password,
      })
      .expect(201);

    expect(res.body).toHaveProperty('accessToken');
    expect(res.body).toHaveProperty('refreshToken');
    expect(res.body).toHaveProperty('user');
    expect(res.body.user).toHaveProperty('email', testUser.email);

    accessToken = res.body.accessToken;
    refreshToken = res.body.refreshToken;
  });

  it('6. GET /profile (Access Profile - Should Succeed)', async () => {
    const res = await request(app.getHttpServer())
      .get('/profile')
      .set('Authorization', `Bearer ${accessToken}`)
      .expect(200);

    expect(res.body).toHaveProperty('email', testUser.email);
    expect(res.body).not.toHaveProperty('password');
  });

  it('7. POST /auth/refresh_token (Rotate Tokens)', async () => {
    const res = await request(app.getHttpServer())
      .post('/auth/refresh_token')
      .send({ refreshToken })
      .expect(201);

    expect(res.body).toHaveProperty('accessToken');
    expect(res.body).toHaveProperty('refreshToken');

    // Save the new tokens
    accessToken = res.body.accessToken;
    refreshToken = res.body.refreshToken;
  });

  it('8. POST /auth/logout (Logout / Revoke Token)', async () => {
    await request(app.getHttpServer())
      .post('/auth/logout')
      .set('Authorization', `Bearer ${accessToken}`)
      .expect(201);

    // Verify refresh token is cleared in database
    const user = await userRepository.findOne({ where: { email: testUser.email } });
    expect(user!.refreshToken).toBeNull();
  });
});
